export {default as Banner} from './Banner'
export {default as Navbar} from './Navbar'
export {default as Services} from './Services'
export {default as Projects} from './Projects'
export {default as Contact} from './Contact'
export {default as Footer} from './Footer'